In [2]:
import numpy as np

In [3]:
arr = [1, 2, 3]
a = np.array(arr)
print(arr)
print(a)

[1, 2, 3]
[1 2 3]


In [4]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
c = np.dot(a.T, b)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[32 38 44 50]


In [6]:
print(np.dot(a.T, a))

14


In [39]:
b = np.arange(25).reshape(5, 5)
b_x = b[:,0:-1]
b_y = b[:,-1]
print(b_x)
print(b_y)

[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]
[ 4  9 14 19 24]
