In [30]:
import numpy as np

In [31]:
arr = [1, 2, 3]
a = np.array(arr)
print(arr)
print(a)

[1, 2, 3]
[1 2 3]


In [35]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [36]:
c = np.dot(a.T, b)
print(b)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[32 38 44 50]


In [37]:
print(np.dot(a.T, a))

14
